auto: true 
server: false 
pygments: false
permalink: none
oauth_client_id: 98fcbba0c51a75bc2585
gatekeeper_url: http://gatekeeper.readingandwritingproject.com
exclude:
- .gitignore
- README.md
- README
